version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exam
      - PGDATA=/var/lib/postgresql/data
volumes:
  db:
    driver: local